# Aliases
alias ll="ls -lh"
alias la="ls -lah"
alias be="bundle exec"
alias du="du -h --max-depth=1"
alias df="df -h"
alias less="less -r"
alias s="screen -DRU"

# Prefix-sensitive history search
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

# Export local env
if [ -f ~/.env ]; then
	for e in $(cat ~/.env); do
		eval export $e
	done
fi
