# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME="candy"

# Aliases
alias du="du -h --max-depth=1"
alias dh="dh -h"
alias s="screen -DRU"

# Disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Plugins
plugins=(git)

# Loads oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Paths and more...