# Path to your oh-my-zsh configuration.
ZSH=/root/.oh-my-zsh

# Theme
ZSH_THEME="candy"

# Load RVM
source /etc/profile

# Aliases
alias du="du -h --max-depth=1"
alias df="df -h"
alias s="screen -DRU"

# Disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Plugins
plugins=(git)

# Loads oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Paths and more...