#! /bin/sh

### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: XXXXXX
# Description:       starts the unicorn web server for application XXXXXX
### END INIT INFO

APP_NAME="XXXXXX"
APP_HOME="/home/$APP_NAME/head"
PID="/var/run/unicorn/$APP_NAME.pid"
UNICORN_OPTS="-c $APP_HOME/config/unicorn.rb -E production -D"

if [ ! -d /var/run/unicorn ]
then
	mkdir /var/run/unicorn
fi

cd $APP_HOME || exit 1

sig () {
	test -s "$PID" && kill -$1 `cat $PID`
}

case "$1" in
start)
	sig 0 && echo >&2 "ERROR: Already running" && exit 0
	cd $APP_HOME
	bundle exec unicorn $UNICORN_OPTS
	echo "Started."
	;;
stop)
	sig QUIT && echo "Stopped." && exit 0
	echo >&2 "ERROR: Not running."
	;;
force-stop)
	sig TERM && echo "Terminated." && exit 0
	echo >&2 "ERROR: Not running."
	;;
restart|reload)
	sig HUP && echo "Reloaded." && exit 0
	echo >&2 "ERROR: Couldn't reload."
	exit 1
	;;
upgrade)
	sig USR2 && echo "Upgraded." && exit 0
	echo >&2 "ERROR: Couldn't upgrade."
	exit 1
	;;
rotate)
	sig USR1 && echo "Logs rotated." && exit 0
	echo >&2 "ERROR: Couldn't rotate logs." && exit 1
	;;
*)
 	echo >&2 "Usage: $0 <start|stop|restart|upgrade|rotate|force-stop>"
 	exit 1
 	;;
esac